name: Exercise tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Go ${{ matrix.go-version }} - ${{ matrix.os }}/${{ matrix.test-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-24.04, windows-2025, macOS-latest]
        test-arch: [amd64]
        race: ["-race"]

        include:
          - go-version: 1.25.x
            test-arch: "386"
            os: ubuntu-24.04
            race: ""
          - go-version: 1.25.x
            test-arch: "386"
            os: windows-2025
            race: ""

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test exercises
        shell: bash
        env:
          GOARCH: ${{ matrix.test-arch }}
        run: ./bin/run-tests
